# semantic/exemplars.py

SCAM_EXEMPLARS = [
    # --- BANK / KYC / OTP SCAMS ---
    "Your account will be blocked if you do not act immediately.",
    "Please share the OTP that was just sent to your phone.",
    "This is an urgent call from your bank's security department.",
    "We need to verify your card details right now.",
    "Your KYC has expired, share your Aadhaar and bank details.",
    "Your credit card has been compromised, please tell me the CVV.",
    "You need to update your PAN card immediately to avoid account suspension.",
    "Apka bank account block ho gaya hai, turant OTP share karein.",
    "Main bank se bol raha hoon, aapka ATM card expire ho raha hai.",
    "KYC update karne ke liye link par click karein aur OTP batayein.",
    "Aapka account freeze hone wala hai, verify karne ke liye details dein.",
    "Sir aapka credit card block ho gaya hai, unblock karne ke liye CVV bataiye.",
    "आपका बैंक खाता ब्लॉक कर दिया जाएगा, कृपया तुरंत ओटीपी बताएं।",
    "मैं बैंक अधिकारी बोल रहा हूँ, आपका एटीएम कार्ड बंद होने वाला है।",
    "अपना केवाईसी अपडेट करने के लिए तुरंत अपने कार्ड का नंबर बताएं।",
    "आपके खाते से पैसे कट गए हैं, रिफंड के लिए लिंक पर क्लिक करें।",
    "अपने क्रेडिट कार्ड के पीछे लिखा सीवीवी (CVV) नंबर हमें बताएं।",

    # --- POLICE / CUSTOMS / LEGAL SCAMS (FedEx Scams) ---
    "There is a legal case against you, pay now to resolve it.",
    "This is the income tax department, you must pay immediately or face arrest.",
    "Your FedEx parcel contains illegal items and has been seized by customs.",
    "This is the police, an arrest warrant has been issued in your name.",
    "Transfer the money to the secure RBI account to avoid legal action.",
    "Yeh police station se call hai, aapke khilaaf arrest warrant hai.",
    "Aapka FedEx courier customs ne rok liya hai, usme illegal items hain.",
    "CBI se bol raha hoon, aapke naam par fraud case darj hua hai.",
    "Turant penalty pay karein warna police aapko arrest karne aa rahi hai.",
    "RBI ke safe account mein paise transfer karein verification ke liye.",
    "मैं पुलिस स्टेशन से बोल रहा हूँ, आपके खिलाफ कानूनी कार्रवाई होगी।",
    "कस्टम विभाग ने आपका पार्सल रोक लिया है, उसमें गैरकानूनी सामान मिला है।",
    "यह सीबीआई से कॉल है, आपके नाम से मनी लॉन्ड्रिंग का केस दर्ज है।",
    "तुरंत जुर्माना भरें वरना पुलिस आपको गिरफ्तार करने आ रही है।",
    "सुप्रीम कोर्ट से वारंट निकला है, केस रफा-दफा करने के लिए पैसे दें।",

    # --- TECH SUPPORT / REMOTE ACCESS SCAMS ---
    "Install this app so I can access your screen remotely.",
    "Download AnyDesk or TeamViewer so I can fix your device.",
    "This is Microsoft tech support, your computer has a virus.",
    "Do not tell anyone about this call, it is confidential.",
    "Open your banking app while sharing your screen with me.",
    "Kripya AnyDesk app download karein KYC update karne ke liye.",
    "Apne phone mein TeamViewer install karein, main yahan se theek kar dunga.",
    "Kisi ko mat batana, yeh ek confidential inquiry hai.",
    "Screen share chalu rakhein aur apna bank app kholiye.",
    "Customer care se bol raha hoon, yeh support app download kar lijiye.",
    "यह एक बहुत ही गोपनीय कॉल है, कृपया किसी को ना बताएं।",
    "अपने फोन में एनीडेस्क (AnyDesk) ऐप डाउनलोड करें ताकि मैं मदद कर सकूं।",
    "मैं कस्टमर केयर से बोल रहा हूँ, आपकी स्क्रीन शेयर करें।",
    "कॉल मत काटना, हमारे साथ लाइन पर बने रहें और ऐप इंस्टॉल करें।",
    "आपकी मशीन हैक हो गई है, उसे ठीक करने के लिए रिमोट एक्सेस दें।",

    # --- LOTTERY / PRIZE / LOAN SCAMS ---
    "You have won a prize, just pay a small processing fee first.",
    "You are eligible for a pre-approved loan of 5 lakh rupees.",
    "To claim your lottery winnings, transfer the GST amount to this account.",
    "Congratulations! You won a brand new car, pay the registration fee now.",
    "Aapki lottery lagi hai, bas thodi processing fee jama kar dein.",
    "Aapko 10 lakh ka pre-approved loan mil raha hai, file charge pay karein.",
    "KBC se bol raha hoon, aap 25 lakh jeet gaye hain, tax bharna padega.",
    "Sir aapko gift mila hai, delivery charge online pay kar dijiye.",
    "आपकी लॉटरी लगी है, बस टैक्स के पैसे अभी ट्रांसफर कर दें।",
    "आपको 5 लाख रुपये का लोन बिना किसी गारंटी के मिल रहा है।",
    "कौन बनेगा करोड़पति से आपकी 25 लाख की लॉटरी लगी है।",
    "आपका लकी ड्रा निकला है, इनाम पाने के लिए पहले प्रोसेसिंग फीस दें।"
]

BENIGN_EXEMPLARS = [
    # --- CASUAL / PERSONAL ---
    "Hi, just calling to check how you're doing.",
    "Can we reschedule our meeting to next week?",
    "What time are we meeting for dinner tonight?",
    "I'll call you back in five minutes, I'm driving right now.",
    "Haan bhai, kal milte hain lunch par.",
    "Kya hum kal ki meeting parso shift kar sakte hain?",
    "Aaj mausam kaisa hai wahan?",
    "Main abhi thoda busy hoon, thodi der mein call karta hoon.",
    "Bhai kahan par pohancha tu? Main wait kar raha hoon.",
    "नमस्ते, मैं बस आपका हालचाल पूछने के लिए कॉल कर रहा था।",
    "क्या हम अपनी मीटिंग का समय बदल सकते हैं?",
    "मैं अभी गाड़ी चला रहा हूँ, थोड़ी देर में कॉल करता हूँ।",
    "मम्मी कैसी हैं? दवाई टाइम पर ले रही हैं ना?",
    "आपसे बात करके बहुत अच्छा लगा, कल फिर बात करते हैं।",

    # --- PROFESSIONAL / WORK ---
    "Did you receive the email I sent regarding the project?",
    "The client meeting has been postponed to 3 PM.",
    "Can you review the pull request when you have a moment?",
    "I've attached the quarterly report for your reference.",
    "Email check kar lena, maine project details bhej di hain.",
    "Kal subah standup meeting mein is par discuss karenge.",
    "Mera code review kar dena jab time mile.",
    "Client ko kal tak presentation bhejni hai.",
    "मैंने आपको प्रोजेक्ट से जुड़ा ईमेल भेज दिया है, चेक कर लीजिएगा।",
    "कल की मीटिंग का समय दोपहर 3 बजे कर दिया गया है।",
    "क्या आपने वो रिपोर्ट पढ़ ली जो मैंने कल भेजी थी?",
    "हम इस विषय पर कल कार्यालय में विस्तार से चर्चा करेंगे।",

    # --- SERVICE / DELIVERY (GENUINE) ---
    "Your order has been shipped and will arrive on Friday.",
    "This is a reminder about your dentist appointment tomorrow.",
    "I am the delivery guy, I'm standing outside your gate.",
    "Your internet service request has been resolved.",
    "Aapka order kal deliver ho jayega, dhanyawad.",
    "Main delivery wala hoon, aapke ghar ke bahar khada hoon.",
    "Aapki internet ki complaint resolve ho gayi hai sir.",
    "Kal aapka doctor ke saath appointment hai, time par aa jana.",
    "आपका सामान भेज दिया गया है और कल तक पहुंच जाएगा।",
    "मैं कूरियर वाला बोल रहा हूँ, कृपया अपना पार्सल ले लें।",
    "कल सुबह 10 बजे आपका अस्पताल में अपॉइंटमेंट है।",
    "आपकी शिकायत दर्ज कर ली गई है, 24 घंटे में समाधान हो जाएगा।"
]